### ISSUE TITLE
ミッションを画像上に記載

### ISSUE THREAD

**Issue by timeshiftseiya** [DiveintoCode-corp/achieve-blogs-seminar#3]

**Comment by norotime** [comment]
@timeshiftseiya 私たちのミッションとビジョン、バリューはこちらです。

ミッション
すべての人が、テクノロジーを武器にして活躍できる社会をつくる。

ビジョン
経験ゼロから稼げるエンジニアになることができるエスカレーターをつくる。

バリュー
・最短経路にこだわる
・稼ぐ機会と仲間、場をつくる
・ひとつ残らずやる
